# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=3.0.0
maven_group=com.sighs
archives_name=stare-till-they-grow
enabled_platforms=fabric,forge
# Minecraft properties
minecraft_version=1.20.1
# Dependencies
fabric_loader_version=0.18.1
fabric_api_version=0.92.6+1.20.1
forge_version=1.20.1-47.3.0
clothconfig_version=11.1.136